version: '3.9'


volumes:
  database: {}


services:

  database:
    container_name: 'memgpt-postgres'
    build:
      context: .
      dockerfile: ./config/docker/dockerfile-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:5432"

  memgpt:
    container_name: 'memgpt'
    build:
      context: .
      dockerfile: ./config/docker/dockerfile-memgpt
      args:
        MEM_USER: ${SYS_USERNAME:-memgpt}
    depends_on:
      - database
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      # Expose the memgpt config folder to the host machine.
      # This allows us to track agents and conversation details in git.
      - ./config/memgpt:/home/${SYS_USERNAME:-memgpt}/.memgpt

      # [1] Dev: Make live changes to the .bashrc file
      - ./config/docker/bashrc.sh:/home/${SYS_USERNAME:-memgpt}/.bashrc
      # [2] Dev: Inspect the current memgpt code
      - ./system:/home/${SYS_USERNAME:-memgpt}/.local/lib/python3.9/site-packages/memgpt
